version: '3'
services:
  web:
    image: node_aws
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "3"
        max-size: "1024m"

  apache: 
    image: httpd:4.2.48
    restart: always
    ports: 
      - 80:80
      - 443:443
    logging: 
      driver: "json-file"
      options: 
        max-size: "1024m"
        max-file: "3"